import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { TanstackQueryProvider } from "@/providers/tanstack-provider"
import { HeroProvider } from "@/providers/hero-ui-provider"
import { SidebarWrapper } from "@/components/landing/sidebar-wrapper"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.className} ${geistMono.variable} bg-background light`}>
                <TanstackQueryProvider>
                    <HeroProvider>
                        <SidebarWrapper>{children}</SidebarWrapper>
                    </HeroProvider>
                </TanstackQueryProvider>
            </body>
        </html>
    )
}
